# Generated by Django 2.2.4 on 2019-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
